# QA GATE — N11-13 (c3abfe8) + N11-6a (83c1c6c)

- **Date**: 2026-08-30
- **Worktree**: `C:\Users\sjkim\orca\workspaces\joseonlike\qa-play3`, branch `CastleBelll/qa-play3`
- **HEAD under test**: `4b14bc6` (merge of `origin/main` @ `83c1c6c`; contains `c3abfe8`)
- **Mode**: read-only QA. No game code was modified. Only two QA harnesses were added
  under `tools/` (`qa_n11_6a.*`, `qa_n11_snap.*`) plus this capture folder.

## Verdict summary

| # | Item | Verdict |
|---|---|---|
| 1 | Pixel snap (c3abfe8) — running motion | **PASS** (+1 new LOW) |
| 1b | Pixel snap — UI/HUD regression | **PASS** |
| 2 | Refine chain shape / lock / unlock / tap-buy / 5-tab layout | **PASS** |
| 2b | Refine cost ladder vs stated contract | **FAIL** (1 LOW) |
| 2c | Refine detail panel copy | **FAIL** (1 MEDIUM, new — not previously reported) |
| 3 | FTUE guide panel vs camp spot labels | **FAIL** — not fixed, and **worse** than previously recorded |

## Environment / preamble

```
git fetch origin && git merge origin/main --no-edit      # ff-only refused, see note
git config core.autocrlf false
git add --renormalize . && git checkout-index --force -a
git ls-files '*.gd' '*.tscn' '*.json' '*.tres' | xargs grep -lU $'\r'   # empty = LF gate PASS
godot --headless --path . --import
godot --headless --path . --script tests/run_tests.gd            # PASS 600/600 tests
godot --headless --path . --script tools/validate_data.gd        # PASS data validation: 19 json files ok
```

**Sync note.** `git merge --ff-only origin/main` was **refused**: the branch was 7 ahead /
3 behind. The 7 local commits were 6 prior-QA merge commits + `dbcf157 chore(qa): landscape
play QA captures` — no game code. Escalated and approved by the coordinator, then merged with
a plain `git merge origin/main`. Verified the merge reverted nothing:
`git diff origin/main HEAD -- scripts/ project.godot data/ tests/` is **empty**.

`export_presets.cfg` still carries CRLF in the working tree after the preamble. It is outside
the `docs/CI.md` gate set (`*.gd/*.tscn/*.json/*.tres`), is only read by `godot --export`, and
holds no multiline string literals — not a gate blocker, noted for the record.

---

## [1] Pixel snap (c3abfe8) — **PASS**

### What is in the build

`project.godot:74-75` — `2d/snap/snap_2d_transforms_to_pixel=true`,
`2d/snap/snap_2d_vertices_to_pixel=true`. Confirmed live at runtime, and the real stage
camera measured at the fractional zoom the commit blames: **`camera zoom = (1.15, 1.15)`**
(`Stage.CAMERA_BASE_ZOOM 1.15 × sqrt(area/design_area)`, exactly 1.15 at the 540×960 design
viewport). `window/stretch/mode="viewport"`, so snapping acts in the 540×960 render space.

### Method

`tools/qa_n11_snap.gd` boots the **real** `scenes/stage.tscn`, freezes the walk cycle
(`AnimatedSprite2D.speed_scale = 0; pause()`) so that any pixel that changes between frames is
the *renderer* moving it and not the animation, disables the player's `_physics_process`, and
drives the body along a deliberately fractional ramp of **0.37 px/frame**. It captures 14
consecutive frames, then repeats the identical ramp with the two snap flags switched **off** at
the viewport (`RenderingServer.viewport_set_snap_2d_{transforms,vertices}_to_pixel`) — an A/B of
the same scene in one process.

Analysis: for each consecutive frame pair, search integer shifts in ±3 px for the alignment that
minimises mean-absolute-difference over a 140×150 crop around the player. **Residual 0 at some
integer shift = the image translated rigidly by whole pixels (correct pixel-art motion).
Residual > 0 = texels resampled between frames (subpixel crawl).**

### Result — the crawl is gone

| snap | aligned residual per frame pair | mean |
|---|---|---|
| **on** | `0.000` on all 13 pairs | **0.0000** |
| **off** | 0.922, 0.861, 1.006, 0.613, 0.550, 0.829, 0.316, 0.287, 0.262, 0.286, 0.129, 0.336, 0.170 | **0.5050** |

With snapping **on**, every frame pair is a pure integer translation — the sprite holds
absolutely still, then jumps a whole pixel. No edge shimmer, no subpixel crawl. With snapping
**off**, no integer shift ever aligns the frames (residual 0.13–1.20), which is precisely the
artifact the owner reported. **The fix works, and it addresses the real cause.**

Frames: `captures/qa-n11-6a/snap/on_f00.png … on_f13.png`, `off_f00.png … off_f13.png`,
positions in `captures/qa-n11-6a/snap/frames.csv`, log `snap/qa_n11_snap.log`.

### NEW LOW — the camera itself is not pixel-locked

Cumulative displacement vs frame 0, snap **on**:

```
dx = [0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 3, 3, 2, 3]
                                ^^^        ^^^   two backward steps
```

The player moves strictly rightward, yet the scene steps **back one pixel** twice. Residual is
`0.000` throughout, so the whole scene (player + ground) moves rigidly together — this is judder,
not shimmer, and it is far less objectionable than the crawl it replaced.

Cause: `scenes/stage.tscn:34-36` — `Camera2D` has `position_smoothing_enabled = true`,
`position_smoothing_speed = 8.0`. The camera's own world position is smoothed and **never
quantised**, so the snapped scene's rounded offset can oscillate by 1 px between frames. This is
a real gameplay condition, not a harness artifact (smoothing runs in the shipped stage).

Severity **LOW** — a clear net improvement over the crawl; worth a follow-up only if the owner
still reports motion roughness. Fix direction: round the camera's own position to whole pixels
(or drive smoothing in integer steps), rather than relying on per-item snapping alone.

### [1b] UI/HUD regression from snapping — **PASS**

Same scene captured with snap on and off at both orientations:

| resolution | pixels differing >8/255 | share |
|---|---|---|
| 540×960 | 2,113 | 0.408 % |
| 960×540 | 4,034 | 0.778 % |

All differences are sub-pixel glyph rasterisation of text. Side-by-side inspection of
`snap/hud_540x960_on.png` vs `snap/hud_540x960_off.png` (and the 960×540 pair) shows **no**
clipping, no misalignment, no missing or shifted element — pause/settings buttons, clock, EXP
bar, Lv/HP readout, kill+scroll counters, the guide panel and the two skill buttons all render
identically. The five-tab meta screen and the camp screen were additionally captured at both
orientations under item [2]/[3] with no snap-induced breakage. `600/600` unit tests and
`19 json` data validation pass on this HEAD.

**Repro**: `godot --path . res://tools/qa_n11_snap.tscn`, then compare `snap/*.png`.

---

## [2] Refine chains (83c1c6c) — **PASS**, with two defects

Harness `tools/qa_n11_6a.gd`; log `captures/qa-n11-6a/qa_n11_6a.log`.
**Repro**: `godot --path . res://tools/qa_n11_6a.tscn`.

### G1 — chain shape — **PASS**

17 refine nodes, exactly **5 roots**, exactly **2 forks**, every node reaches a root, no cycles,
no node with more than one prerequisite.

```
공격  refine_attack_damage    -> attack_speed -> crit_chance -> crit_damage
술법  refine_skill_power      -> area_scale -> burn_power -> (chain_amount | seal_haste)   FORK
생존  refine_max_hp           -> defense
신속  refine_move_speed       -> magnet_radius -> (xp_gain | luck)                          FORK
투사  refine_projectile_speed -> projectile_count
```

### G2 — cost ladder — **FAIL (LOW)**

First-cost band is **70 … 360 냥**, matching the commit. Prerequisite-cost rule holds: every
child's first cost rises above its parent's. Rank growth is x2.0 on 16 of 17 nodes.

> **FINDING L-1 (LOW).** `refine_move_speed` rank 1→2 is **80 → 150 = ×1.875**, not ×2.0.
> Every other node in the tab uses ×2.0, and commit `83c1c6c` states "rank growth x2.0".
> `data/meta_tree.json`, node `refine_move_speed`, `costs: [80, 150, 300, 600, 1200]` —
> ranks 2→5 are ×2.0, so only the first step is off. Player-visible effect: rank 2 of 신속
> is 10 냥 cheaper than the ladder advertises.
>
> Related: the `_refine_note` string in `data/meta_tree.json` `config` still reads
> **"랭크 성장 x2.2"**, which contradicts both the shipped data (×2.0) and the commit message.
> Stale doc string inside the shipped data file.

**Repro**: `python -c "import json;d=json.load(open('data/meta_tree.json',encoding='utf-8'));n=[x for x in d['nodes'] if x['id']=='refine_move_speed'][0];print(n['costs'])"` → `[80, 150, 300, 600, 1200]`.

### G3 — radial layout, 5 tabs × 2 orientations — **PASS**

| tab | 540×960 | 960×540 |
|---|---|---|
| 공용 (trunk) | 17 nodes, min gap 62.0 px | 17 nodes, 62.0 px |
| **연마 (refine)** | 17 nodes, min gap 62.0 px | 17 nodes, 62.0 px |
| 우치 (taoist) | 15 nodes, 62.0 px | 15 nodes, 62.0 px |
| 석주 (warrior) | 10 nodes, 62.0 px | 10 nodes, 62.0 px |
| 월영 (archer) | 10 nodes, 62.0 px | 10 nodes, 62.0 px |

Disc is 56.0 px (no fallback shrink triggered), contract is disc + 4 px = 60.0 px — **every tab
clears it at 62.0 px**. No disc leaves the canvas at either orientation. Every chain node's
prerequisite is present on the same canvas, so no link is drawn to a missing parent.

Captures: `g3_540x960_{trunk,refine,taoist,warrior,archer}.png`,
`g3_960x540_{...}.png`.

The chain links render as designed (`g4_refine_fresh.png`): a hub at centre, five solid gold
branches to the five roots, dashed dim vines curling outward to the locked chain nodes.

### G4 — locked/dashed display — **PASS**

Fresh profile (empty `meta_tree`): exactly the **5 roots** are buyable (wood ring), and exactly
the **12** chain nodes draw in `CARD_BORDER_DIM` → dashed vine. Capture `g4_refine_fresh.png`.

### G5 — unlock propagation — **PASS**

Walking the 술법 chain one purchase at a time, each buy opens **exactly** its own children and
nothing else; the fork opens both branches together:

```
bought refine_skill_power (rank 1) -> newly buyable: refine_area_scale
bought refine_area_scale  (rank 1) -> newly buyable: refine_burn_power
bought refine_burn_power  (rank 1) -> newly buyable: refine_chain_amount, refine_seal_haste
```

Capture `g5_arts_chain_open.png`.

### G6 — cost text — **PASS on the numbers**, but see M-1

Every root quotes its data cost in both locales — 80/80/70/90/100 냥, matching
`MetaTree.next_cost`. Captures `g6_cost_ko.png`, `g6_cost_en.png`.

> **FINDING M-1 (MEDIUM, new — not in any prior gate).** On the 연마 tab the detail panel's
> info line reads **"` 전용 · 선택한 수행자에게만 적용`"** (en: **"` only · applies to that
> cultivator`"**) — with an **empty character name** before it.
>
> Two problems, one cause:
> 1. **It is factually wrong.** Refine nodes carry no `character` field (verified: zero of the
>    17 have one), and `MetaTree.aggregate_effects` skips the character filter when
>    `node_character(entry)` is empty — so every 연마 node applies to **all** characters. The
>    panel tells the player that a global permanent upgrade is exclusive to one cultivator.
> 2. **The string is malformed**, leading with a blank where the name belongs.
>
> Cause: `scripts/ui/meta_tree_screen.gd:815-820`, `_detail_info_line()` special-cases only
> `TAB_TRUNK`; the `_refine` tab falls through to
> `UiLocale.text("meta.branch_only_fmt") % MetaTree.display_name(_characters.get(_current_tab, {}), …)`.
> `_characters` has no `"_refine"` key, so `display_name({}, locale)` returns `""`.
> The trunk tab correctly shows `meta.permanent`; 연마 should too (or its own string).
>
> **Repro**: 수련 → 연마 tab → tap any node → read the line under the node name. Visible in
> `g6_cost_ko.png` / `g6_cost_en.png` and in the harness log G6 section.

### R-1 regression — a tap really buys — **PASS**

Driven with a genuine `InputEventMouseButton` press/release at the disc's own screen rect, so
hit-testing runs:

| resolution | tap result | buy result |
|---|---|---|
| 540×960 | tab stays `_refine`, selected `refine_max_hp`, CTA live | rank 0→**1**, gold 4000→**3930** (cost 70) ✓ |
| 960×540 | tab stays `_refine`, selected `refine_max_hp`, CTA live | rank 0→**1**, gold 4000→**3930** (cost 70) ✓ |

The tab is no longer thrown away by a refine-node tap, and the purchase completes with the exact
data cost debited. Captures `g7_bought_540x960.png`, `g7_bought_960x540.png`.

---

## [3] FTUE guide panel over camp spot labels — **FAIL, worse than previously recorded**

**Still present, and broader than the earlier LOW.** The earlier note recorded portrait-only
overlap. Measured in the **shipped state** it also breaks landscape.

Why the earlier reading was too kind: `scripts/ui/camp_screen.gd:124-128` hides
`Layout/Frame/BottomBar` while the archivist speaks (QA F-17). Hiding the bar **re-flows the map
layer downward**, pushing spots further into the panel. A measurement taken with the bar still
visible understates the overlap and shows landscape as clean. With the bar hidden, as it is in
the real first-visit flow:

| resolution | locale | spots covered | detail |
|---|---|---|---|
| 540×960 | ko | **3** | 훈련장(training) **100 %**, 약방(apothecary) 83 %, 저자(market) 83 % |
| 540×960 | en | **3** | training **100 %**, apothecary 85 %, market 85 % |
| 960×540 | ko | **4** | 공적비(stele) 68 %, 훈련장 68 %, 약방 68 %, 저자(market) **94 %** |
| 960×540 | en | **4** | stele 68 %, training 68 %, apothecary 68 %, market **94 %** |

Panel is bottom-anchored at `[P:(16,650) S:(508,190)]` portrait / `[P:(16,384) S:(928,148)]`
landscape (`GuideDialog.PANEL_BOTTOM_MARGIN 120 / PANEL_HEIGHT 190`, landscape `24 / 132`),
while the camp's lower-yard spots sit at y≈665–769 portrait and y≈361–380 landscape.

The spot **name labels** (초하 under 약방, 너름 under 저자, 범강 under 훈련장 …) sit below each
icon and are therefore **completely hidden** — the player meets the archivist on their very first
camp visit and reads the map with three or four of its stations sliced off.

Captures: `g8_ftue_540x960_ko.png`, `g8_ftue_540x960_en.png`, `g8_ftue_960x540_ko.png`,
`g8_ftue_960x540_en.png`.

**Repro**: fresh profile (no `archivist_met` flag) → enter 본거지 → the 묵헌 welcome opens over
the map. Or `godot --path . res://tools/qa_n11_6a.tscn` and read the G8 section.

**Severity**: LOW→**MEDIUM**. It is transient (one dialog, dismissed by 다음) and blocks no
input, but it lands on the one screen the FTUE exists to explain, and it hides the NPC names
that the guide is introducing.

---

## Findings, ranked

| id | sev | item | finding |
|---|---|---|---|
| **M-1** | MEDIUM | [2] | 연마 tab detail line claims a global upgrade is character-exclusive, with a blank name — `_detail_info_line()` has no `_refine` case (`meta_tree_screen.gd:815-820`) |
| **M-2** | MEDIUM | [3] | Archivist welcome panel covers 3 camp spots portrait / 4 landscape, hiding their NPC name labels; not fixed, and landscape is affected once the bottom bar is hidden as shipped |
| **L-1** | LOW | [2] | `refine_move_speed` rank 1→2 is ×1.875 (80→150), not the stated ×2.0; and `_refine_note` in `data/meta_tree.json` still says "랭크 성장 x2.2" |
| **L-2** | LOW | [1] | `Camera2D` position smoothing is not pixel-quantised, so the snapped scene steps back 1 px twice in 14 frames; rigid whole-scene judder, no shimmer |

Nothing found blocks the two commits: the pixel-snap fix does what it claims and breaks no UI,
and the refine chain ships the shape, locking, unlocking, pricing and tap-to-buy behaviour the
commit describes.

## Artifacts

```
captures/qa-n11-6a/REPORT.md            this file
captures/qa-n11-6a/qa_n11_6a.log        item [2]/[3] machine-readable log
captures/qa-n11-6a/g3_*.png             5 tabs x 2 orientations
captures/qa-n11-6a/g4_refine_fresh.png  locked/dashed state
captures/qa-n11-6a/g5_arts_chain_open.png
captures/qa-n11-6a/g6_cost_{ko,en}.png
captures/qa-n11-6a/g7_bought_*.png      R-1 tap-and-buy
captures/qa-n11-6a/g8_ftue_*.png        FTUE overlap, 2 res x 2 locales
captures/qa-n11-6a/snap/{on,off}_f00..13.png   pixel-snap A/B frames
captures/qa-n11-6a/snap/hud_*_{on,off}.png     HUD A/B
captures/qa-n11-6a/snap/frames.csv             per-frame positions
captures/qa-n11-6a/snap/qa_n11_snap.log
tools/qa_n11_6a.gd / .tscn              item [2]/[3] harness (QA only, no game code)
tools/qa_n11_snap.gd / .tscn            item [1] harness (QA only, no game code)
```
