# QA GATE — N11-5 장터 창고 (Storehouse)

- **Target commit**: `dc5b0cb feat(camp): the market keeps a storehouse of banked materials (N11-5)`
- **Branch under test**: `CastleBelll/qa-play3` @ `ab46e45` (merge of `origin/main`)
- **Game-code diff vs origin/main**: 0 (`git diff origin/main HEAD -- scripts/ scenes/ data/ tests/ tools/` empty, no tracked modifications)
- **Mode**: read-only QA. No game code changed. The only new files are the QA harness `tools/qa_n11_5.gd` / `.tscn` and these captures.
- **Date**: 2026-08-31
- **Evidence log**: `captures/qa-n11-5/qa_n11_5.log`

## Verdict

| Item | Result |
|---|---|
| [1] 진입·표시 | **FAIL** — 1 finding (F-1). Routing, rows, counter, ko/en × portrait/landscape all PASS. |
| [2] 숫자 정확성 | **PASS** |
| [3] 정렬·문구 | **PASS** |
| [4] 회귀 | **PASS** |

**Findings: 1 (F-1, MEDIUM).** No CRITICAL, no HIGH. Nothing blocks the feature functionally; F-1 is a dead/misplaced empty-state string.

## Baseline verification (all green)

```
godot --headless --path . --import
godot --headless --path . --script tests/run_tests.gd     -> PASS 609/609 tests
godot --headless --path . --script tools/validate_data.gd -> PASS 19 json files ok
godot --path . res://tools/locale_check.tscn              -> LOCALE CHECK: PASS
                                                             (171 entries, 0 mismatched specifiers;
                                                              94 call sites, 0 untranslated)
godot --path . res://tools/layout_sweep.tscn              -> PASS 14 screens x 11 devices x 2 locales,
                                                             nothing overflows, clips or scrolls
```

`docs/CI.md` preamble is intact (4.7-stable requirement, import-first, the autoload `_ready()` runner gap).

---

## [1] 진입·표시 — FAIL (1 finding)

| Check | Result | Evidence |
|---|---|---|
| G1a 장터(너름) spot routes to `scenes/storehouse.tscn` | PASS | `CampScreen.MAP_SPOTS` market entry carries `"scene": "res://scenes/storehouse.tscn"`; the scene instances a `StorehouseScreen` |
| G1b empty profile still lists the billed rows | PASS | 14 rows on a default profile — every one of the 14 loot kinds is billed by unbought recipes / rank-0 training |
| G1c header counter | PASS | reads `0/14` on an empty pouch; `14/14` after a full-pouch reboot |
| G1d '선반이 비었다…' notice on an empty profile | **FAIL — F-1** | notice hidden on a fresh profile |
| G1e ko/en × 540×960 + 960×540 overflow/clip | PASS | 0 clipped labels, 0 horizontal spill in all four combinations; portrait = 1 column, landscape = 2 columns |

Rows carry name + demand line + count pill as specified; the shopping-list intent holds (rows appear at count 0 when something bills the material).

Screens: `g1_storehouse_ko_portrait.png`, `g1_storehouse_ko_landscape.png`, `g1_storehouse_en_portrait.png`, `g1_storehouse_en_landscape.png`.

### F-1 (MEDIUM) — the '선반이 비었다' first-run copy is unreachable on a first run, and fires only at endgame where it reads wrong

`scripts/ui/storehouse_screen.gd:141` ties the notice to the row list:

```gdscript
_empty_label.visible = rows.is_empty()
```

`Storehouse.rows()` keeps a material when the pouch holds it **or** when something still bills it. On a default profile every one of the 14 loot kinds is billed (22 unbought recipes + rank-0 training), so `rows` is never empty and the notice never shows. Measured: `empty profile: rows=14 counter='0/14' empty_notice_visible=false`.

The one state that does show it is the opposite of what the copy describes: every recipe unlocked, every training rank maxed, pouch empty → `rows=0 notice_visible=true`, and the screen then tells a finished player "선반이 비었다. 밤에서 주워 온 것이 여기 쌓인다." / "The shelves are bare. Whatever the night gives up is stored here." — first-run onboarding copy shown only to an endgame player.

The gate asked for both the notice **and** the billed rows on a fresh profile. They are mutually exclusive as written.

Evidence: `g1_storehouse_ko_portrait.png` (fresh profile — 14 rows, no notice) vs `g1_empty_notice_endgame_only.png` (maxed + empty pouch — notice, no rows).

**Repro**
1. Fresh profile (no materials, no `mod_unlocks`, no `meta_tree` ranks).
2. 본거지 → 장터(너름) → 창고.
3. Observe: 14 rows, all `0개 … 모자라다`, header `0/14`, no '선반이 비었다' line.
4. Now set every `mod_unlocks` id and max every `meta_tree` rank, pouch `{}`, re-enter: the notice appears on an otherwise blank screen.

**Fix direction (not applied — read-only gate)**: gate the notice on the pouch rather than the row list (e.g. `stocked_count(...) == 0`), so it rides above the shopping list on a fresh profile; and give the truly-empty endgame state its own line.

### Observation O-1 (LOW, no action needed) — dead row payload

`Storehouse.rows()` (`scripts/core/storehouse.gd:24-25`) builds `"desc"` and `"special"` into every row dict; `StorehouseScreen._build_row()` never reads either. Harmless, but the flavour text is computed and thrown away.

### Observation O-2 (INFO) — the screen scrolls

14 rows × 72px minimum overflows 540×960, so the storehouse scrolls in portrait. This is intentional: `tools/layout_sweep.gd:32` registers `storehouse` in `LIST_SCREENS` alongside 명부수/괴이록/공적비/대장간, and the owner's no-scroll rule exempts list screens. Landscape reflows to 2 columns.

---

## [2] 숫자 정확성 — PASS

| Check | Result | Evidence |
|---|---|---|
| G2a count pill matches profile | PASS | seeded odd counts 1,3,5,…,27 across all 14 kinds; every pill matched (`1개`/`x1` … `27개`/`x27`) |
| G2b billed total vs independent recompute | PASS | see below |
| G2c a smithy unlock drops exactly that recipe's share | PASS | unlocked `bongmageom_mod` (bill `{cinnabar: 2}`) via the real screen button; cinnabar demand 9 → 7, everything else unchanged |
| G2d a training rank purchase swaps to the next rank's bill | PASS | `burn_mastery` rank0 `{dokkaebi_flame: 1}` → rank1 `{dokkaebi_flame: 2}`; total moved by exactly −1+2 |

The independent recompute sums straight off raw `data/*.json` inside the harness (`_expected_demand`), never calling `Storehouse.demand`, so the screen's number is compared against something rather than against itself. Both sides:

```
Storehouse.demand: whetstone 11, ghost_iron 11, fire_spirit_stone 13, thunder_stone 8,
                   cinnabar 9, dokkaebi_flame 10, talisman_paper 22, beast_fang 8,
                   wonhon_shard 12, bamboo 10, tough_fiber 11, cast_iron 2,
                   willow_branch 2, raw_egg 1
independent sum:   (identical, 14 kinds)
```

Cross-check on demand semantics: unlocked recipes and bought ranks bill nothing; only unbought recipes and each node's *next* rank count. Verified on both edges — a fully-unlocked, fully-maxed profile owes 0 kinds.

Screens: `g2_after_unlock.png`, `g2_after_rank.png`.

---

## [3] 정렬·문구 — PASS

| Check | Result | Evidence |
|---|---|---|
| G3a short-first ordering | PASS | 7 short rows (count 0) all above 7 stocked rows (count 99); ties break by stock desc then id |
| G3b all three copy states reachable | PASS | 모자라다 7 rows, 충분하다 7 rows on one profile; 지금 쓸 곳 없음 1 row on a maxed profile |
| G3c measured card contrast ≥ 4.5:1 | PASS | 17 labels measured off the rendered frame; **worst 5.54:1** |
| G3d N11-4 F-3 ink rule | PASS | dim (unstocked) card detail = full `INK #1a1613`; bright (stocked) card detail = `TEXT_MUTED_ON_PAPER #5e564c` — on every row |
| G3e count pills | PASS | `CountPill` 5.72:1, `StockPill` 5.72:1 |

Measured samples (rendered pixels, WCAG 2.1 relative luminance):

```
bamboo/Name      stocked=false token=#1a1613 ground=#b09d80  6.83:1
bamboo/Detail    stocked=false token=#1a1613                 6.84:1
cast_iron/Detail stocked=true  token=#5e564c                 5.54:1   <- worst
CountPill '7/14'                                             5.72:1
StockPill '0개'                                              5.72:1
```

The F-3 rule from the previous gate holds exactly as written in `storehouse_screen.gd:180-183`: the dimmed empty-shelf plate takes full ink, the bright stocked plate takes muted.

Screens: `g3_states_ko_portrait.png` (short + enough), `g3_spare_ko_portrait.png` (지금 쓸 곳 없음), `g3_contrast_ko_portrait.png`.

---

## [4] 회귀 — PASS

| Check | Result | Evidence |
|---|---|---|
| G4a smithy unlock reasons still separate | PASS | broke → `gold`, funded-but-empty-pouch → `materials`, stocked → `ok` |
| G4b smithy screen | PASS | 22 recipe cards, counter `0/22`, 0 clipped labels |
| G4c 수련 연마 tab | PASS | `Tab__refine` pressed, `_current_tab='_refine'`, 0 clipped labels |
| G4d 본거지 spot routing | PASS | all 8 spots resolve — 5 scenes (all exist), 막사 select, and NPC-voice spots with an npc id |
| G4e FTUE 환영 상단 앵커 | PASS | `anchor_top=true`, panel top y = **16.0** of 960 (top band, not the lower yard) |
| G4f save round trip (N11-4 F-1/F-2) | PASS | 14 material kinds, `mod_unlocks`, and gold all survive serialize → deserialize → migrate |
| G4g rebooted storehouse reads the loaded pouch | PASS | counter `14/14` after the reboot |

G4e note: the FTUE dialog refuses to open on a harness profile (`is_harness_profile()` returns the write lock), so the harness lifts the write lock for that one mount **after copying the real `user://profile.save` aside**, and restores it immediately afterwards. The player's save file is untouched.

Also checked: every one of the 14 billed materials is referenced by at least 2 non-`loot.json` data files, so no shopping-list row points at a material nothing drops.

Screens: `g4_smithy_ko_portrait.png`, `g4_meta_ko_portrait.png`, `g4_meta_refine_tab.png`, `g4_camp_ko_portrait.png`, `g4_storehouse_after_reboot.png`.

---

## How to re-run this gate

```sh
godot --headless --path . --import
godot --path . res://tools/qa_n11_5.tscn      # writes captures/qa-n11-5/*.png + qa_n11_5.log
```

The harness seeds throwaway profiles with `SaveService._write_locked = true`, uses a `user://qa_n11_5_probe.save` probe file for the round trip (deleted after read), and never writes the player's profile.

## Captures

| File | What it shows |
|---|---|
| `g1_storehouse_ko_portrait.png` | fresh profile, ko, 540×960 — 14 shopping-list rows, **no empty notice** (F-1) |
| `g1_storehouse_ko_landscape.png` | fresh profile, ko, 960×540 — 2 columns |
| `g1_storehouse_en_portrait.png` / `..._en_landscape.png` | same in English |
| `g1_empty_notice_endgame_only.png` | the only state that shows '선반이 비었다' — maxed + empty pouch (F-1) |
| `g2_after_unlock.png` | storehouse after a real smithy unlock |
| `g2_after_rank.png` | storehouse after a real 수련 rank purchase |
| `g3_states_ko_portrait.png` | 모자라다 above 충분하다 |
| `g3_spare_ko_portrait.png` | 지금 쓸 곳 없음 |
| `g3_contrast_ko_portrait.png` | frame the contrast numbers were measured from |
| `g4_smithy_ko_portrait.png` | smithy regression |
| `g4_meta_ko_portrait.png` / `g4_meta_refine_tab.png` | 수련 screen, 연마 tab open |
| `g4_camp_ko_portrait.png` | camp with the FTUE welcome, top-anchored |
| `g4_storehouse_after_reboot.png` | storehouse reading a profile that came back off disk |
